export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const REQUEST_EMPLOYEES_LIST = 'REQUEST_EMPLOYEES_LIST';
export const EMPLOYEES_LIST_SUCCESS = 'REQUEST_EMPLOYEES_LIST';
export const EMPLOYEES_LIST_FAILURE = 'REQUEST_EMPLOYEES_LIST';